name: PlatformIO CI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          owner: intuitiva-io
          repo: teste-update-release
          tag_name: 1.0.21
          release_name: Release 1.0.21
          commitish: main
          body: |
            Release 1.0.21

          draft: false
          prerelease: false

