name: PlatformIO CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: |
            .pio/build/nodemcu-32s/firmware.bin
            bodyRelease.md

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Get latest tag
        id: latest_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Checkout repository release
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}-releases
          token: ${{ secrets.GH_TOKEN }}
          ref: main

      - name: create tag
        run: |
          git tag ${{ env.tag }}
          git push origin ${{ env.tag }}
          
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: firmware
          
      - name: Check if file exists and read content
        id: file_check
        run: |
          if [[ -f "bodyRelease.md" ]]; then
            echo "body=$(cat bodyRelease.md)" >> $GITHUB_ENV
          else
            echo "body=Release ${{ env.tag }}" >> $GITHUB_ENV
          fi
        shell: bash

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          owner: intuitiva-io
          repo: teste-update-releases
          tag_name: ${{ env.tag }}
          release_name: Release ${{ env.tag }}
          commitish: main
          body: |
            # Release ${{ env.tag }}
            ${{ env.body }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset-linux
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url}}
          asset_path: .pio/build/nodemcu-32s/firmware.bin
          asset_name: firmware.bin
          asset_content_type: application/octet-stream
