name: Releases

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: creat
      run: echo "teste" > README.md
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "README.md"
        body: "body.md"